### ISSUE TITLE
Plugin returns 1 - not working

### ISSUE THREAD

**Issue by Koshmaar** [NHDaly/tmux-scroll-copy-mode#12]
Hi, so I run the manual installation - 

mkdir ~/tmux-plugins
git clone https://github.com/nhdaly/tmux-scroll-copy-mode ~/tmux-plugins

Have in my .tmux.conf:

```
set-option -g mouse on
bind r source-file ~/.tmux.conf; display "PC> Reloaded .tmux conf"
setw -g mode-keys vi
# https://github.com/NHDaly/tmux-scroll-copy-mode
run-shell ~/tmux-plugins/tmux-scroll-copy-mode/scroll_copy_mode.tmux
```

When I reload using ctrl+B r I get:
'/home/hrutkows/tmux-plugins/tmux-scroll-copy-mode/scroll_copy_mode.tmux' returned 1

Not suprisingly, scrolling using mouse wheel doesn't work. Any idea what might be wrong?

I have Tmux 2.1 running on cygwin, on Windows 8.1  x64 .

**Comment by NHDaly** [comment]
This is a bit surprising. With just `set-option -g mouse on` and without the plugin, do you have any mouse support at all? Can you click to change panes or change windows for instance?

Also, after entering copy-mode with `<prefix>-[`, does the mouse-wheel work for scrolling?

**Comment by Koshmaar** [comment]
Correct :) I can change windows by clicking in the bottom bar, and panes. Also in the copy mode, I can scroll with mouse wheel.

**Comment by NHDaly** [comment]
Hi again. So this might very likely have been related to issue #13. Would you mind updating the plugin (by `git pull`ing it from your ~/tmux-plugins directory) and see if you still have the issue?

Also, can you paste here what your WheelUpPane and WheelDownPane bindings are by running `tmux list-keys -T root`? For an example, mine look like this:

```
$ tmux list-keys -T root
...
bind-key -T root WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if-shell -Ft= '#{alternate_on}' 'send-keys -M' "if -Ft= '#{pane_in_mode}' ' send-keys -M ; send-keys -M ; ' ' copy-mode -e -t='""
bind-key -T root WheelDownPane    if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if-shell -Ft= '#{alternate_on}' 'send-keys -M' "if -Ft= '#{pane_in_mode}' ' send-keys -M ; send-keys -M ; ' ' send-keys -M ; send-keys -M ; '""
```

Thanks!

**Comment by Koshmaar** [comment]
Hi, so I update git repo, reloaded and unfortunately still have the same error msg. Maybe we should add some logging, to see what's the stacktrace and where it's failing?

As for the keys, theese are all I have:

> ```
> bind-key -T root MouseDown1Pane   select-pane -t = ; send-keys -M
> bind-key -T root MouseDown1Status select-window -t =
> bind-key -T root MouseDown3Pane   select-pane -m -t =
> bind-key -T root MouseDrag1Pane   if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
> bind-key -T root MouseDrag1Border resize-pane -M
> ```

I tried it with plugin on and off - same. No WheelUpPane.

**Comment by NHDaly** [comment]
Yeah I think logging is a good idea. I don't have easy access to a windows or cygwin. Would you be able to try?

I've pushed up a branch [`logging`](https://github.com/NHDaly/tmux-scroll-copy-mode/compare/logging), which just has a bunch of added log statements printing to stderr. Feel free to change those if they're not sufficient.

Hopefully you can just run the script by navigating to the plugin and:

```
git checkout logging
./scroll_copy_mode.tmux
```

For me, the output was

```
$ ./scroll_copy_mode.tmux
Entering scroll_copy_mode.tmux
Entering helpers.sh
Entering bind_wheel_up_to_enter_copy_mode
Calling get_tmux_option(@scroll-down-exit-copy-mode, on)
Calling get_tmux_option(@scroll-in-moused-over-pane, on)
Calling get_tmux_option(@scroll-without-changing-pane, off)
Calling get_tmux_option(@scroll-speed-num-lines-per-scroll, 3)
Calling get_tmux_option(@prevent-scroll-for-fullscreen-alternate-buffer, off)
Got tmux options. e.g. scroll_down_to_exit: on
About to run awk for num_lines_per_scroll
Finished deducing settings. About to set tmux bind-key commands.
Done!
```

I also added log statements to `only_scroll_sometimes.sh`, but unfortunately i don't know where those would print to. (tmux calls that while executing its key-press for scrolling.)

Let me know if you find anything interesting! :) Thanks for your help.

**Comment by Koshmaar** [comment]
OK I found it:

```
$ ./scroll_copy_mode.tmux
./scroll_copy_mode.tmux: line 2: $'\r': command not found
Entering scroll_copy_mode.tmux
./scroll_copy_mode.tmux: line 4: $'\r': command not found
./scroll_copy_mode.tmux: line 6: $'\r': command not found
: No such file or directoryne 7: .

$ dos2unix scroll_copy_mode.tmux

$ ./scroll_copy_mode.tmux
Entering scroll_copy_mode.tmux
Entering helpers.sh
./scripts/helpers.sh: line 2: $'\r': command not found
./scripts/helpers.sh: line 3: syntax error near unexpected token `$'{\r''
'/scripts/helpers.sh: line 3: `log() {
./scroll_copy_mode.tmux: line 16: log: command not found
./scroll_copy_mode.tmux: line 18: get_tmux_option: command not found
./scroll_copy_mode.tmux: line 19: get_tmux_option: command not found
./scroll_copy_mode.tmux: line 20: get_tmux_option: command not found
./scroll_copy_mode.tmux: line 21: get_tmux_option: command not found
./scroll_copy_mode.tmux: line 22: get_tmux_option: command not found
./scroll_copy_mode.tmux: line 24: log: command not found
./scroll_copy_mode.tmux: line 43: log: command not found
awk: cmd. line:1: { print ( >= 1) }
awk: cmd. line:1:           ^ syntax error
./scroll_copy_mode.tmux: line 46: [: -eq: unary operator expected
awk: cmd. line:1: { print ( >= 0) }
awk: cmd. line:1:           ^ syntax error
./scroll_copy_mode.tmux: line 50: [: -eq: unary operator expected
./scroll_copy_mode.tmux: line 57: log: command not found
./scroll_copy_mode.tmux: line 67: log: command not found

$ dos2unix scripts/helpers.sh
```

**Now the output is as yours, and scrolling tmux panes works!**

So the issue was that the checked out files had dos line endings (as it should be, since I'm developing on win, and git does the conversion like that), while my cygwin (babun flavour) was expecting unix line endings. Thanks for your help, just calling the script would be enough to show the error.

One more thing: so I can scroll, but as soon as I select some text (using tmux mouse selection), the scrolling resets back to bottom. **Do you know if it's possible to disable that?**

**Comment by NHDaly** [comment]
!! Glad to hear it. Yeah, windows can be a bit tricky like that. :) If you checked it out with git inside cygwin would that have avoided the problem?

Glad you've solved it!

**Comment by NHDaly** [comment]
> One more thing: so I can scroll, but as soon as I select some text (using tmux mouse selection), the scrolling resets back to bottom. **Do you know if it's possible to disable that?**

Currently it is not, no. See this issue for more details: tmux/tmux/issues/140.

**Comment by Koshmaar** [comment]
I did check it out with git inside cygwin :) That's how git is setup to handle EOL.

Ok, so currently not, but I see someone is working on this. So there is hope. Thanks for all!

**Comment by NHDaly** [comment]
:) No problem! Enjoy!!
