### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by yan12125** [NHDaly/tmux-scroll-copy-mode#2]
The main script is `scroll_copy_mode.tmux` rather than `tmux_scroll_copy_mode.tmux`. [Manual Installation](https://github.com/NHDaly/tmux-scroll-copy-mode#manual-installation) section should be updated.

**Comment by NHDaly** [comment]
Thanks! Fixed in 8ad6bb95670529ec9e831b1609ac6ee75f16de05.
