### ISSUE TITLE
emulate-scroll-for-no-mouse-alternate-buffer doesn't work for git diff

### ISSUE THREAD

**Issue by gmvi** [NHDaly/tmux-scroll-copy-mode#25]
I'm on maxOS X Sierra and am using iTerm

Scrolling in `less` works fine (as in, scroll events are captured and arrow keys are sent to `less`), but scrolling in `git diff` doesn't, and I have to use e.g. `git diff HEAD --color=always | less -R` instead of `git diff HEAD`

**Comment by NHDaly** [comment]
huh, strange. This works for me (`OSX El Capitan, 10.11.6` and `iTerm 2 Build 3.0.13`).

Let's do some more version games:
```
$ git --version
git version 2.10.0
```

```
$ cd ~/.tmux/plugins/tmux-better-mouse-mode
$ git show --oneline -s
4c686e5 Fixed quotes in bind-key WheelDownPane causing #23.
```

```
$ tmux -V
tmux 2.3
```

I'll try to get access to a macOS Sierra machine to double check. Do any of these other things stand out as different to you?

**Comment by gmvi** [comment]
My git version is 2.11.0, that's the only difference other than Sierra. I'll install git 2.10 to test that this weekend.

**Comment by NHDaly** [comment]
Huh, interesting... I'm on a macOS Sierra machine now, (`macOS 10.12.2`), and it's still working for me.

Everything else is still the same for me, except git is slightly different:
```
$ git --version
git version 2.10.1 (Apple Git-78)
```

I'll try git 2.11.0 now

**Comment by NHDaly** [comment]
Ah bummer. I installed git from homebrew, and it's still working, so i'm not sure what could be going on.

```
$ git --version
git version 2.11.0
```

Any other ideas?

**Comment by NHDaly** [comment]
Actually, can you start by posting your tmux key-bindings?

For me they look like this:

```
$ tmux list-keys -T root
bind-key -T root MouseDown1Pane   select-pane -t = ; send-keys -M
bind-key -T root MouseDown1Status select-window -t =
bind-key -T root MouseDown3Pane   if-shell -F -t = #{mouse_any_flag} "select-pane -t=; send-keys -M" "select-pane -mt="
bind-key -T root MouseDrag1Pane   if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key -T root MouseDrag1Border resize-pane -M
bind-key -T root WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "         if -Ft= '#{alternate_on}'           "send-keys up ; send-keys up ; "           "                          if -Ft= '#{pane_in_mode}'               'send-keys -M ; send-keys -M ; '               'copy-mode -e -t= ; send-keys -M ; send-keys -M ; '           "       "
bind-key -T root WheelDownPane    if-shell -F -t = #{mouse_any_flag} "send-keys -M" "         if -Ft= "#{alternate_on}"           "send-keys down ; send-keys down ; "           " send-keys -M ; send-keys -M ; "       "
```

It's just the last two that we care about. And the bits that translate the scrolls into keypresses are ` if -Ft= '#{alternate_on}'           "send-keys up ; send-keys up ; " ` and ` if -Ft= "#{alternate_on}"           "send-keys down ; send-keys down ; " `.

**Comment by gmvi** [comment]
My key bindings look the same, except for a third of each "send-keys" command in WheelUpPane and WheelDownPane. But I just realized this is also an issue outside of tmux. :/ I only assumed it was related to tmux because I discovered it right after installing this plugin. It's an issue in both iTerm and terminal.app too. Maybe it's a git config issue? Something about the way git is invoking less?

Thanks for the help, guess I'll look elsewhere :)

**Comment by NHDaly** [comment]
Oh makes sense. Good luck!

Actually, can I ask you a favor: when you find out your configuration issue, would you please still post it here? It might be a common one.


I'm imagining it might be that there's a different key set to scroll up and down in your git diff, for example, and it would be nice if this plugin could figure that out and send the right key! :)

**Comment by NHDaly** [comment]
Hi again, @gmvi, did you ever figure this out? Someone else is having the same issue at #27.

Do you think you could try looking at these [pager settings](https://git-scm.com/docs/git-config#git-config-corepager) to see if they shine any light on your problem?:

```
$ echo $GIT_PAGER
$ git config --get-all core.pager  # I think this is how you check this? For me it's empty...
$ echo $PAGER
$ echo $LESS
```

Thanks! :D

**Comment by gmvi** [comment]
`$GIT_PAGER` is empty
`git config --get-all core.pager` is empty
`$PAGER` is `less`
`$LESS` is empty
