### ISSUE TITLE
Some settings incompatible with tmux 2.4

### ISSUE THREAD

**Issue by puppetjoy** [NHDaly/tmux-scroll-copy-mode#29]
So far I have found that the `scroll-speed-num-lines-per-scroll` and `scroll-without-changing-pane` settings have no effect on tmux 2.4.  They worked in 2.3.  This may have something to do with some new(?) default bindings:

```
bind-key    -T copy-mode    WheelUpPane       select-pane ; send-keys -X -N 5 scroll-up
bind-key    -T copy-mode    WheelDownPane     select-pane ; send-keys -X -N 5 scroll-down
bind-key    -T copy-mode-vi WheelUpPane       select-pane ; send-keys -X -N 5 scroll-up
bind-key    -T copy-mode-vi WheelDownPane     select-pane ; send-keys -X -N 5 scroll-down
```

Other settings like `emulate-scroll-for-no-mouse-alternate-buffer` seem to be working still in tmux 2.4.

**Comment by NHDaly** [comment]
Hey, sorry it took me so long to get to this. I believe this should be all fixed now! See #33.

Please let me know if you're still having any problems?
