### ISSUE TITLE
Regressions in 2.4, 2.5: @scroll-without-changing-pane and @scroll-speed-num-lines-per-scroll

### ISSUE THREAD

**Issue by NHDaly** [NHDaly/tmux-scroll-copy-mode#33]
See #32:
- [x] setting `@scroll-without-changing-pane` doesn't seem to do that in tmux v2.5.

More regressions:
- [x] `@scroll-speed-num-lines-per-scroll` isn't respected.
- [x] If both `@scroll-in-moused-over-pane` and `@scroll-without-changing-pane` are `'off'`, scrolling in a different pane still enters `copy-mode` in the current pane. Is that desired?
- [x] `@scroll-in-moused-over-pane` is ignored -- always scrolls in moused over pane.
- [x] `@scroll-down-exit-copy-mode` is ignored -- always doesn't exit copy-mode now.

**Comment by NHDaly** [comment]
Actually, lots of compatibility problems. Probably started in `v2.4`. Put the check-list in the first comment.

**Comment by henrythiemann** [comment]
Regarding `@scroll-speed-num-lines-per-scroll`, I found something in the tmux [changelog](https://github.com/tmux/tmux/blob/master/CHANGES) that may help (from the 2.3 to 2.4 changes):
```
The emacs-copy and vi-copy tables have been replaced by the copy-mode and
copy-mode-vi tables. Commands are sent using the -X and -N flags to
send-keys. So the following:

  bind -temacs-copy C-Up scroll-up
  bind -temacs-copy -R5 WheelUpPane scroll-up

Becomes:

  bind -Tcopy-mode C-Up send -X scroll-up
  bind -Tcopy-mode WheelUpPane send -N5 -X scroll-up
```

I was able to set it to scroll one line at a time using:
```
bind -Tcopy-mode WheelUpPane send -N1 -X scroll-up
bind -Tcopy-mode WheelDownPane send -N1 -X scroll-down
```

**Comment by NHDaly** [comment]
Beautiful, thank you. I just came across this myself, and was gonna try it; thanks for doing that for me! :)

It looks like i'll finally have to start adding some version checks in the script of the sort "if version >= 2.4, do this, else do that." :(

Probably about time, though... I'll take off the `help-wanted` tag for now while I look into that, then. Thanks!! :)

**Comment by NHDaly** [comment]
Fixed scroll speed, but it's still broken for partial scroll speeds (speeds < 1).

Thanks @henrythiemann

**Comment by NHDaly** [comment]
It looks like that last commit also fixed `@scroll-without-changing-pane`. So that's good.

`@scroll-in-moused-over-pane` doesn't work now though (it's always set to true). I've updated the check-boxes at the top.
Also `@scroll-down-exit-copy-mode`. (never exits)

**Comment by NHDaly** [comment]
Okay! haha sorry for the spam. I think actually the last commit fixed everything. It all seems to work for me now in `v2.4`! :)

I think my testing had just messed up some of the bindings and I didn't realize it. After a tmux reset, all the options seem to work for me now! :) Thanks!

**Comment by NHDaly** [comment]
Let me know if anyone else still has problems.
