### ISSUE TITLE
Can't get tmux to scroll at less than 3 lines per scroll (tmux 2.2, ubuntu 16.04)

### ISSUE THREAD

**Issue by arooni** [NHDaly/tmux-scroll-copy-mode#37]
Here's my config:

```
# from https://github.com/NHDaly/tmux-scroll-copy-mode
set -g @scroll-speed-num-lines-per-scroll .1
set -g @prevent-scroll-for-fullscreen-alternate-buffer "on"
set -g @scroll-without-changing-pane "on"
```

# i have tried different values per scroll from 1 on down and yet my tmux seems determined to scroll at 3 lines per scroll

# in order to slow down scroll in other apps like chrome I have  xinput set-prop 10 "Evdev Scrolling Distance" 4 1 1 in my ~/.profile ;; not sure if that affects anything.  running a logitech mx anywhere mouse.  

Love the idea of this; if only I could get it to work :)

**Comment by NHDaly** [comment]
Hmmm, yeah I'm actually not sure if the values less than one (the decimal values) are working anymore...

But were you at least able to get less than 3? I see you're setting `@scroll-speed-num-lines-per-scroll` to `0.1`. Did it affect anything when you set it to the whole-number `1`? or `2`? or `10`, for that matter?

**Comment by arooni** [comment]
I still have at 0.5 and apparently that's working... combined to adjusting ev scrolling distance.  So anyway I'm a happy camper I'll close this issue out.
