### ISSUE TITLE
Scroll too fast after I did the configuration.

### ISSUE THREAD

**Issue by wqtty** [NHDaly/tmux-scroll-copy-mode#4]
I'm on Mac using iTerm2 logging on to a ubuntu server, working within tmux2.1 on the server side, with a Logitech wireless mouse.
The problem is it still scrolls way too fast even after I set the line number to 1 according to the readme file.

here are the lines:
set-option -g mouse on
set -g @scroll-down-exit-copy-mode "on"
set -g @scroll-without-changing-pane "on"
set -g @scroll-speed-num-lines-per-scroll "1"

**Comment by NHDaly** [comment]
Sorry for the delay. I think this is now fixed. Please let me know if this works for you! :)

Try setting your scroll speed to "0.5" or "0.33" to see if it's any better. Is this kind of what you had in mind?

**Comment by wqtty** [comment]
I finally figured out that it's my Logitech mouse's fault......its driver has some "scroll acceleration" feature....I have moved to magic trackpad2(LOL) and everything works great now.
Thanks for the reply.

**Comment by NHDaly** [comment]
Okay no problem! Well anyway I added an option to slow down scrolling
anyway! :)
