### ISSUE TITLE
Option to disable going into copy mode when application has secondary screen (less,man...)

### ISSUE THREAD

**Issue by SageEx** [NHDaly/tmux-scroll-copy-mode#6]
As the title says, when scrolling in `less` and `man` pages, it should not go into copy-mode.
Can it be done by any configuration ?
Or better yet, make it into a default option.

**Comment by NHDaly** [comment]
I dunno! That's a good idea. Maybe you could ask on [tmux/tmux](http://www.github.com/tmux/tmux) as well and link to the Issue from here?

**Comment by SageEx** [comment]
Well, I go into copy mode with mouse wheel scroll up. So, I thought if on wheel up you could check for the current program( `less`, `man`..) and then decide if you should go into copy mode. 
There are scripts to pass certain keystrokes to tmux which checks current program, and since this is a plugin, maybe you could explicitly check for these programs and then go into copy mode.
I thought this is a plugin behaviour issue, and hence this issue.
This is a particular behaviour for a specific use case -  are you sure this is a tmux issue?

**Comment by NHDaly** [comment]
yes i agree, that sounds reasonable! I just don't know how to do it. No, I didn't mean it's a tmux issue, but rather that they might know how to help. Maybe the tmux-users forum is the right place to ask.

Anyway, I'll play around with it if I get free time, but I'm not sure if it's possible. Cool idea though!

**Comment by NHDaly** [comment]
Jk! You're right it's not hard at all. I think I've got it working but I
have to leave now. I'll finish it and upload it when I get back! :)

**Comment by SageEx** [comment]
Cool, thanks. I'll be waiting.

**Comment by NHDaly** [comment]
Great suggestion, thanks! I think it's an improvement. This defaults to "off" now, but can be enabled with:
set -g @prevent-scroll-for-fullscreen-alternate-buffer 'on'

(Note, I found the inspiration for this fix from https://github.com/tmux/tmux/issues/168).

**Comment by SageEx** [comment]
Works Perfect , Thanks a lot !!!

**Comment by TxHawks** [comment]
Just for future reference, it should be `set -g @prevent-scroll-for-fullscreen-alternate-buffer 'on'`, not `@prevent-scroll-for-fullscreen-alternate-buffer = 'on'` (i.e. sans the `=`), right?

**Comment by NHDaly** [comment]
Oops, yes it should. Thanks!

**Comment by ghost** [comment]
Thank you for this! (about to try it)

**Comment by ghost** [comment]
This is amazing!
