### ISSUE TITLE
scrolling mousewheel gives error

### ISSUE THREAD

**Issue by TxHawks** [NHDaly/tmux-scroll-copy-mode#7]
After installing the plugin and reloading the conf file, I get the following when scrolling the mouse:
`Usage: copy-mode [-Mu] [-t target-pane]`

Mouse-related options in config file:

``` tmux
set -g mouse-utf8 on 
set -g mouse on      
```

**Comment by corv89** [comment]
Can you check that you've got tmux 2.1 by running `tmux -V`?

tmux 2.1 should support `copy-mode -e`

**Comment by TxHawks** [comment]
I'm using 2.1

**Comment by corv89** [comment]
What happens when you open the tmux command prompt (Ctrl-b + : ) and run `copy-mode -e`?

**Comment by TxHawks** [comment]
Same message as above

**Comment by NHDaly** [comment]
Hmm, that's definitely weird. In that case, it doesn't sound like this plugin is to blame... Have you asked on the tmux repo?

**Comment by NHDaly** [comment]
Was this ever resolved?

**Comment by TxHawks** [comment]
@NHDaly -

Not yet. I need to try and ask at the tmux repo. Will update if I manage to figure it out.

**Comment by NHDaly** [comment]
Cool.
I think it would also help, actually if you could paste here what your WheelUpPane and WheelDownPane bindings are by running `tmux list-keys -T root`. For an example, mine look like this:

```
$ tmux list-keys -T root
...
bind-key -T root WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if-shell -Ft= '#{alternate_on}' 'send-keys -M' "if -Ft= '#{pane_in_mode}' ' send-keys -M ; send-keys -M ; ' ' copy-mode -e -t='""
bind-key -T root WheelDownPane    if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if-shell -Ft= '#{alternate_on}' 'send-keys -M' "if -Ft= '#{pane_in_mode}' ' send-keys -M ; send-keys -M ; ' ' send-keys -M ; send-keys -M ; '""
```

Thanks! :)

**Comment by TxHawks** [comment]
The output of `tmux list-keys -T root` is:

``` bash
bind-key -T root MouseDown1Pane   select-pane -t = ; send-keys -M
bind-key -T root MouseDown1Status select-window -t =
bind-key -T root MouseDrag1Pane   if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key -T root MouseDrag1Border resize-pane -M
bind-key -T root WheelUpPane      if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if-shell -Ft= '#{alternate_on}' 'send-keys -M' "if -Ft= '#{pane_in_mode}' ' send-keys -M ; send-keys -M ; send-keys -M ; ' ' copy-mode -e -t='""
bind-key -T root WheelDownPane    if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if-shell -Ft= '#{alternate_on}' 'send-keys -M' "if -Ft= '#{pane_in_mode}' ' send-keys -M ; send-keys -M ; send-keys -M ; ' ' send-keys -M ; send-keys -M ; send-keys -M ; '""
```

There seem to be two extra `send-keys -M`s in `WheelUpPane` and `WheelDownPane`, compared with yours.

Thanks!

**Comment by NHDaly** [comment]
> There seem to be two extra send-keys -Ms in WheelUpPane and WheelDownPane, compared with yours.

Oh, yeah, that's because I've set `@scroll-speed-num-lines-per-scroll` to `2` instead of the default, `3`. Sorry that's confusing.

Yep, plugin looks okay, so it's gotta be something with your `tmux`. I'm gonna close this Issue for now, but feel free to open it again if you're stuck in the future. Good luck! :)
