### ISSUE TITLE
Fails on stock FreeBSD; depends on bash

### ISSUE THREAD

**Issue by corv89** [NHDaly/tmux-scroll-copy-mode#8]
After adding the appropriate `run-source` to my .tmux.conf and running `tmux source ~/.tmux.conf` I get:

`'/tmux_scroll_copy/scroll_copy_mode.tmux' returned 127`

Turns out the script depends on bash being available.

I think it would be best to add a note of the dependency to the readme or remove it altogether if nothing bash specific is needed.

Thank you for the plugin!

**Comment by NHDaly** [comment]
No problem. So is this because the script starts with `#!/usr/bin/env bash`? If I get rid of that line will that solve your problem? If not, can you just send me a pull request that sets this up to work cross-platform if you know what is required? Thanks!

**Comment by corv89** [comment]
I will give it a try

**Comment by corv89** [comment]
I've submitted my PR, now the plugin should be POSIX compliant.

Note that haven't tested it on Linux.
